export const projectKeysMap: { [key: string]: string } = {
  name: "Project",
  symbol: "Symbol",
  launch_date: "Launch date",
  category_tags: "Category tags",
  price: "Price ($)",
  price_24h_change: "24h price change (%)",
  price_7d_change: "7d price change (%)",
  price_30d_change: "30d price change (%)",
  price_90d_change: "90d price change (%)",
  price_180d_change: "180d price change (%)",
  price_ath: "ATH ($)",
  price_atl: "ATL ($)",
  volume_24h: "Volume 24h ($)",
  market_cap_circulating: "Circulating market cap latest ($)",
  market_cap_fully_diluted: "Fully-diluted market cap latest ($)",
  volmc_ratio: "Volume / MC ratio (%)",
  tvl: "TVL latest ($)",
  tvl_24h_change: "24h TVL change (%)",
  tvl_7d_change: "7d TVL change (%)",
  tvl_30d_change: "30d TVL change (%)",
  tvl_90d_change: "90d TVL change (%)",
  tvl_180d_change: "180d TVL change (%)",
  tvl_7d: "7d avg. TVL ($)",
  tvl_30d: "30d avg. TVL ($)",
  tvl_90d: "90d avg. TVL ($)",
  tvl_180d: "180d avg. TVL ($)",
  gmv_annualized: "Annualized GMV ($)",
  revenue_7d: "7d total revenue ($)",
  revenue_7d_change: "7d total revenue change (%)",
  revenue_30d: "30d total revenue ($)",
  revenue_30d_change: "30d total revenue change (%)",
  revenue_90d: "90d total revenue ($)",
  revenue_90d_change: "90d total revenue change (%)",
  revenue_180d: "180d total revenue ($)",
  revenue_180d_change: "180d total revenue change (%)",
  revenue_protocol_7d: "7d protocol revenue ($)",
  revenue_protocol_7d_change: "7d protocol revenue change (%)",
  revenue_protocol_24h: "24h protocol revenue ($)",
  revenue_protocol_24h_change: "24h protocol revenue change (%)",
  revenue_protocol_30d: "30d protocol revenue ($)",
  revenue_protocol_30d_change: "30d protocol revenue change (%)",
  revenue_protocol_90d: "90d protocol revenue ($)",
  revenue_protocol_90d_change: "90d protocol revenue change (%)",
  revenue_protocol_180d: "180d protocol revenue ($)",
  revenue_protocol_180d_change: "180d protocol revenue change (%)",
  ps: "P/S ratio latest (x)",
  ps_24h_change: "24h P/S change (%)",
  ps_7d_change: "7d P/S change (%)",
  ps_30d_change: "30d P/S change (%)",
  ps_90d_change: "90d P/S change (%)",
  ps_180d_change: "180d P/S change (%)",
  ps_7d: "7d avg. P/S ratio (x)",
  ps_30d: "30d avg. P/S ratio (x)",
  ps_90d: "90d avg. P/S ratio (x)",
  ps_180d: "180d avg. P/S ratio (x)",
  twitter_followers: "Twitter followers latest",
  revenueSupplySide: "Supply-side revenue ($}",
  revenueProtocol: "Protocol revenue ($}",
  revenue_protocol: "Protocol revenue ($}",
  revenue_supply_side: "Supply-side revenue ($}",
  market_cap: "Market cap ($}",
  revenue_protocol_annualized: "Protocol revenue annualized",
  revenue_annualized: "Revenue annualized",
  token_incentives: "Token incentives ($)",
}
